# The URL the site will be built for
base_url = "https://www.idrokin.com/"
title = "IDrokin"

minify_html = true
# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# Theme name in the /themes directory
theme = "pico"

taxonomies = [
    {name = "tags"},
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "css"

[search]
index_format = "elasticlunr_json"

[extra]
author = "Igor Drokin"
description = "Igor Drokin's Blog"
index_page="home"
top_menu = ["home","projects","posts"]
copyright_string = "Сreated by Igor Drokin in 2025 – %YEAR% for fun. Powered by [zola](https://getzola.org/) and [pico](https://github.com/kuznetsov17/pico)."
nonce=""
avatar_src = "images/avatar.png"
logo_src = "images/logo.webp"

[extra.giscus]
data_repo="LyricalToxic/blog-idrokin"
data_repo_id="_"
data_category="General"
data_category_id="_"
data_mapping="url"
data_strict="0"
data_reactions_enabled="0"
data_emit_metadata="0"
data_input_position="bottom"
data_lang="en"
crossorigin="anonymous"
src="https://giscus.app/client.js"

[extra.footer.icons]
github = "https://github.com/LyricalToxic"
linkedin = "https://www.linkedin.com/in/igor-drokin-822233227/"